language: julia
julia:
  - nightly
notifications:
  email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --check-bounds=yes -e "Pkg.clone(pwd()); Pkg.test(\"CLI\"; coverage=true)"
after_success:
    - julia -e "cd(Pkg.dir(\"CLI\")); Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(Coveralls.process_folder())"

